# R 文法確認ノートブック

## 代入と四則演算

In [1]:
# 代入記号として = を使用することも可能ですが，　
# Rでは一般的に <- を用いるのが一般的です．

x<-3
x

[1] 3

In [2]:
2-1

[1] 1

In [3]:
2*3

[1] 6

In [4]:
4/2

[1] 2

In [5]:
3^4

[1] 81

In [6]:
3**4

[1] 81

### メモ：複数の処理を一度に行いたい場合はセミコロン；で繋いでコードを書きます．

In [7]:
2-1;2*3;4/2;3^4;3**4

[1] 1

[1] 6

[1] 2

[1] 81

[1] 81

In [8]:
x=0
x=x+1
x

[1] 1

In [9]:
#どうやらダメっぽい
x+=1

ERROR: Error in parse(text = x, srcfile = src): <text>:2:3:  予想外の '=' です 
1: #どうやらダメっぽい
2: x+=
     ^


# ベクトルと行列

In [ ]:
x_vector <- c(1, 2, 3, 4, 5)
x_vector

In [ ]:
length(x_vector)

## 要素アクセス

In [ ]:
vec <- c(10,9,8,7,6,5,4,3,2,1)
vec

In [ ]:
# 添え字と要素の結果の関係に注意
vec[1]; vec[3]; vec[10]

In [ ]:
# スライスによるアクセス
vec[4:8]

## 演算

In [ ]:
# 加法と減法
vec1<-c(1,3,5)
vec2<-c(2,4,6)
vec1+vec2; vec1-vec2

In [ ]:
#スカラー倍
scalar=3
#　Rでは変数名にピリオド　.　を用いて良い．
x.vector<-c(2,1,0)
scalar*x.vector

In [ ]:
# * と /　
# 各々の要素に演算が適用される
vec1*vec2;vec1/vec2

## 要素の結合

In [ ]:
# 結合
joined<-append(vec1,vec2)
joined

## vec<- c(....) がめんどくさい

In [ ]:
mendokusai<-c(1,2,3,4,5,6,7,8,9,10)
rakuchin<-c(1:10)
mendokusai
rakuchin
all(mendokusai==rakuchin)

In [ ]:
vec<-1:10
vec

## ドキュメンテーション

In [10]:
help(c)

# 行列

In [11]:
elements<-c(1,2,3,4,5,6)
matrix(elements,2,3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [12]:
matrix(elements,nrow=2,ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [13]:
#3行2列　オプション引数を省略してもいいらしい
matrix(elements,nrow=3,2)

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [14]:
#2行3列．可読性を考えると望ましくない書き方である
matrix(elements,3,nrow=2)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [15]:
#どちらかのみを指定してOK
matrix(elements,2)
matrix(elements,ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## 情報取得

In [16]:
mat<-matrix(elements,nrow=2,ncol=3)
ncol(mat)
nrow(mat)
dim(mat)

[1] 3

[1] 2

[1] 2 3

## データアクセス

In [17]:
mat<-matrix(elements,nrow=2,ncol=3)
mat
#2行3列目の値
mat[2,3]
#1行目の要素を取り出す
mat[1,]
#3列目の要素を取り出す
mat[,3]
#2列目から3列目までの要素を取り出す
mat[,2:3]

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 6

[1] 1 3 5

[1] 5 6

[,1] [,2]
[1,] 3    5   
[2,] 4    6

In [18]:
# ~以外のを取り出す
#1行以外
mat[-1,]
#3列以外
mat[,-3]
#2列目から3列目までの要素以外
mat[,-(2:3)]

[1] 2 4 6

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] 1 2

## 演算

In [19]:
mat<-matrix(elements,nrow=2,ncol=3)
mat+1
2*mat

[,1] [,2] [,3]
[1,] 2    4    6   
[2,] 3    5    7

[,1] [,2] [,3]
[1,] 2    6    10  
[2,] 4    8    12

In [20]:
elements.1<-c(1,3,5,7,9,11)
elements.2<-c(2,4,6,8,10,12)
mat.1<-matrix(elements.1,2,3)
mat.2<-matrix(elements.2,2,3)
mat.1; mat.2

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 3    7    11

[,1] [,2] [,3]
[1,] 2    6    10  
[2,] 4    8    12

In [21]:
mat.1+mat.2; mat.1-mat.2

[,1] [,2] [,3]
[1,] 3    11   19  
[2,] 7    15   23

[,1] [,2] [,3]
[1,] -1   -1   -1  
[2,] -1   -1   -1

In [22]:
# 要素ごとに演算がブロードキャストされる
mat.1*mat.2;mat.1/mat.2

[,1] [,2] [,3]
[1,]  2   30    90 
[2,] 12   56   132

[,1] [,2]      [,3]     
[1,] 0.50 0.8333333 0.9000000
[2,] 0.75 0.8750000 0.9166667

## 行列の転置

In [23]:
mat
t(mat)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

## label を付与する

In [24]:
mat

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [25]:
colnames(mat)<-c("c1","c2","c3")
mat

c1 c2 c3
[1,] 1  3  5 
[2,] 2  4  6

In [26]:
rownames(mat)<-c("r1","r2")
mat

c1 c2 c3
r1 1  3  5 
r2 2  4  6

## ドキュメンテーション

In [27]:
help(matrix)

# 統計値算出

In [28]:
x<-1:5
x

[1] 1 2 3 4 5

In [29]:
#max min
max(x); min(x)

[1] 5

[1] 1

In [30]:
#平均
sum(x);sum(x)/length(x);mean(x)

[1] 15

[1] 3

[1] 3

In [31]:
#分散，標準偏差
var(x); sd(x)

[1] 2.5

[1] 1.581139

In [32]:
#中央値
median(x)

[1] 3

In [33]:
income.a<-c(100,200,300,400,500)
mean(income.a); median(income.a)

[1] 300

[1] 300

In [34]:
income.b<-c(100,200,300,400,100000)
mean(income.b);median(income.b)

[1] 20200

[1] 300

## 一気に見たいんです

In [35]:
x
# 1st Qu 　=下側25％点
# 3rd Qu = 上側25％点
summary(x)

[1] 1 2 3 4 5

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       2       3       3       4       5 

# 2次元配列の統計値算出

In [36]:
mat<-matrix(1:12,nrow=3,ncol=4,byrow=TRUE)
mat

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

## 要素全ての統計値

In [37]:
sum(mat);sum(1:12)

[1] 78

[1] 78

In [38]:
mean(mat);mean(1:12)

[1] 6.5

[1] 6.5

## 行ごと，列ごとの統計値

In [39]:
rowSums(mat);　colSums(mat)

[1] 10 26 42

[1] 15 18 21 24

In [40]:
rowMeans(mat);　colMeans(mat)

[1]  2.5  6.5 10.5

[1] 5 6 7 8

## apply function
```
apply(X,MARGIN,FUN)
MARGIN	
a vector giving the subscripts which the function will be applied over. E.g., for a matrix 1 indicates rows, 2 indicates columns, c(1, 2) indicates rows and columns. Where X has named dimnames, it can be a character vector selecting dimension names.
```

In [41]:
help(apply)

In [42]:
apply(mat,1,sum)
apply(mat,2,sum)

[1] 10 26 42

[1] 15 18 21 24

In [43]:
summary(mat)

       V1          V2           V3           V4    
 Min.   :1   Min.   : 2   Min.   : 3   Min.   : 4  
 1st Qu.:3   1st Qu.: 4   1st Qu.: 5   1st Qu.: 6  
 Median :5   Median : 6   Median : 7   Median : 8  
 Mean   :5   Mean   : 6   Mean   : 7   Mean   : 8  
 3rd Qu.:7   3rd Qu.: 8   3rd Qu.: 9   3rd Qu.:10  
 Max.   :9   Max.   :10   Max.   :11   Max.   :12  

In [44]:
apply(mat,1,summary); apply(mat,2,summary)

[,1] [,2] [,3] 
Min.    1.00 5.00  9.00
1st Qu. 1.75 5.75  9.75
Median  2.50 6.50 10.50
Mean    2.50 6.50 10.50
3rd Qu. 3.25 7.25 11.25
Max.    4.00 8.00 12.00

[,1] [,2] [,3] [,4]
Min.    1     2    3    4  
1st Qu. 3     4    5    6  
Median  5     6    7    8  
Mean    5     6    7    8  
3rd Qu. 7     8    9   10  
Max.    9    10   11   12